version: '3.9'

services:
  db:
    image: postgres:14
    container_name: moodle_db
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: moodle_pgadmin
    restart: always
    env_file: .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db

  moodle:
    build:
      context: ./moodle
      dockerfile: Dockerfile
      args:
        MOODLE_VERSION: ${MOODLE_VERSION}
    container_name: moodle_app
    restart: always
    env_file: .env
    volumes:
      - ./data/moodledata:/var/www/moodledata

  nginx:
    image: nginx:latest
    container_name: moodle_nginx
    restart: always
    ports:
      - "${MOODLE_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/moodledata:/var/www/moodledata
    depends_on:
      - moodle
